services:
  db:
    image: postgres:17
    container_name: inventory-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory
      TZ: Europe/Rome
    volumes:
      - /home/napalmz/docker-conf/home-inventory/pgdata17:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventory"]
      interval: 5s
      retries: 5
    restart: always

  backend:
    image: napalmzrpi/home-inventory-backend:latest
    container_name: inventory-backend
    environment:
      TZ: Europe/Rome
      DATABASE_URL: postgresql://admin:admin@db:5432/inventory
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory
      FASTAPI_ROOT_PATH: /api
    volumes:
      - /home/napalmz/docker-conf/home-inventory/backups:/app/backups
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    image: napalmzrpi/home-inventory-frontend:latest
    container_name: inventory-frontend
    environment:
      TZ: Europe/Rome
      BACKEND_BASE_URL: http://backend:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always