services:
  db:
    image: postgres:15
    container_name: inventory-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory
      TZ: Europe/Rome
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventory"]
      interval: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: inventory-backend
    environment:
      TZ: Europe/Rome
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    entrypoint: ["/app/entrypoint.sh"]

  frontend:
    build: ./frontend
    container_name: inventory-frontend
    environment:
      TZ: Europe/Rome
      VITE_BACKEND_BASE_URL: http://localhost:8001
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: