"""add type field to inventories

Revision ID: 4ef54a6a9ff5
Revises: 
Create Date: 2025-05-12 10:33:11.292778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef54a6a9ff5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###

    from sqlalchemy.sql import table, column
    from sqlalchemy import String

    inventories = table('inventories', column('type', String))
    op.execute(inventories.update().values(type="INVENTORY"))
    op.alter_column('inventories', 'type', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'type')
    # ### end Alembic commands ###