"""add type field to inventories

Revision ID: 4ef54a6a9ff5
Revises: 
Create Date: 2025-05-12 10:33:11.292778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef54a6a9ff5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table("inventories"):
        return

    inventory_columns = {col["name"] for col in inspector.get_columns("inventories")}
    if "type" not in inventory_columns:
        op.add_column('inventories', sa.Column('type', sa.String(), nullable=True))

    from sqlalchemy.sql import table, column
    from sqlalchemy import String

    inventories = table('inventories', column('type', String))
    op.execute(inventories.update().where(column('type').is_(None)).values(type="INVENTORY"))
    op.alter_column('inventories', 'type', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'type')
    # ### end Alembic commands ###