"""add filter_templates

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-03-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON

# revision identifiers, used by Alembic.
revision = 'e5f6a7b8c9d0'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filter_type', sa.String(length=32), nullable=False),
    sa.Column('criteria', JSON(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False, server_default=sa.literal(False)),
    sa.Column('data_ins', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('data_mod', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    sa.Column('user_ins', sa.Integer(), nullable=True),
    sa.Column('user_mod', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_ins'], ['users.id']),
    sa.ForeignKeyConstraint(['user_mod'], ['users.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id', 'name', name='uq_filter_templates_inventory_name'),
    if_not_exists=True
    )
    op.create_index(op.f('ix_filter_templates_inventory_id'), 'filter_templates', ['inventory_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_filter_templates_id'), 'filter_templates', ['id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filter_templates_id'), table_name='filter_templates')
    op.drop_index(op.f('ix_filter_templates_inventory_id'), table_name='filter_templates')
    op.drop_table('filter_templates')
    # ### end Alembic commands ###
